services:
  mongodb:
    image: mongo:latest
    container_name: order_db
    ports:
      - "27019:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: